// Generated by Claude (claude-sonnet-4-6)
package com.aifinance.adapter.in.web.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * 대시보드 실시간 피드 한 줄. 계좌 id 대신 에이전트 이름으로 변환해 전달한다.
 */
public record FeedItem(
        Long id,
        String senderName,
        String receiverName,
        BigDecimal amount,
        String type,
        String description,
        LocalDateTime createdAt
) {}
