// Generated by Claude (claude-sonnet-4-6)
package com.aifinance.adapter.in.web;

import com.aifinance.adapter.in.web.dto.FeedItem;
import com.aifinance.application.port.out.AgentPort;
import com.aifinance.application.port.out.LedgerPort;
import com.aifinance.application.port.out.TransferPort;
import com.aifinance.domain.agent.Agent;
import com.aifinance.domain.ledger.EntryType;
import com.aifinance.domain.transfer.Transfer;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * 대시보드 화면을 위한 조회 전용 API.
 *  - GET /feed  : 최신 거래 20건 (에이전트 이름 + LLM 사유 포함)
 *  - GET /stats : 총 거래 건수 / 총 송금액 / 총 잔액 / 에이전트 수
 */
@RestController
public class DashboardController {

    private final TransferPort transferPort;
    private final AgentPort agentPort;
    private final LedgerPort ledgerPort;
    private final FeedSseService feedSseService;

    public DashboardController(TransferPort transferPort, AgentPort agentPort, LedgerPort ledgerPort, FeedSseService feedSseService) {
        this.transferPort = transferPort;
        this.agentPort = agentPort;
        this.ledgerPort = ledgerPort;
        this.feedSseService = feedSseService;
    }

    @GetMapping("/feed/stream")
    public SseEmitter stream() {
        return feedSseService.subscribe();
    }

    @GetMapping("/feed")
    public List<FeedItem> feed() {
        Map<Long, String> nameByAccountId = agentPort.findAll().stream()
                .collect(Collectors.toMap(a -> a.getAccount().getId(), Agent::getName, (a, b) -> a));

        return transferPort.findRecent().stream()
                .map(t -> new FeedItem(
                        t.getId(),
                        nameByAccountId.getOrDefault(t.getSender().getId(), "익명"),
                        nameByAccountId.getOrDefault(t.getReceiver().getId(), "익명"),
                        t.getAmount(),
                        t.getType().name(),
                        t.getDescription(),
                        t.getCreatedAt()
                ))
                .toList();
    }

    @GetMapping("/stats")
    @Transactional(readOnly = true) // 차변/대변 합을 같은 스냅샷에서 읽어 순간적 불일치 방지
    public Map<String, Object> stats() {
        List<Agent> agents = agentPort.findAll();
        BigDecimal totalBalance = agents.stream()
                .map(a -> a.getAccount().getBalance())
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        // 복식부기 무결성: 실제 원장 테이블에서 차변/대변 합산 → 항상 일치해야 함
        BigDecimal totalDebit = ledgerPort.sumByType(EntryType.DEBIT);
        BigDecimal totalCredit = ledgerPort.sumByType(EntryType.CREDIT);

        return Map.of(
                "totalTransfers", transferPort.count(),
                "totalMoved", transferPort.sumAmount(),
                "totalBalance", totalBalance,
                "agentCount", agents.size(),
                "totalDebit", totalDebit,
                "totalCredit", totalCredit,
                "balanced", totalDebit.compareTo(totalCredit) == 0
        );
    }
}
