// Generated by Claude (claude-sonnet-4-6)
package com.aifinance.adapter.in.web;

import org.springframework.stereotype.Component;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * SSE 브로드캐스트 서비스. 거래 발생 시 연결된 모든 클라이언트에 즉시 push.
 */
@Component
public class FeedSseService {

    private final List<SseEmitter> emitters = new CopyOnWriteArrayList<>();

    public SseEmitter subscribe() {
        SseEmitter emitter = new SseEmitter(0L); // no timeout
        emitters.add(emitter);
        emitter.onCompletion(() -> emitters.remove(emitter));
        emitter.onTimeout(()  -> emitters.remove(emitter));
        emitter.onError(e     -> emitters.remove(emitter));
        return emitter;
    }

    /** json 문자열을 모든 연결된 클라이언트에 전송 */
    public void publish(String json) {
        List<SseEmitter> dead = new ArrayList<>();
        for (SseEmitter emitter : emitters) {
            try {
                emitter.send(SseEmitter.event().data(json));
            } catch (IOException e) {
                dead.add(emitter);
            }
        }
        emitters.removeAll(dead);
    }
}
